- public/stylesheets/style.css
- views/layout.pug
- views/partials/footer.pug
Created a footer in pug and changed layout.pug to incorporate footer into pages.
> Frontend design footer

- controllers/event.js
- routes/event.js
- test/account.js
- test/basic.js
- test/common.js
- test/event.js
- views/event/create.pug
This PR adds the code for creating events. 
@spkane31 the thing I'd appreciate it if you did is look at the test cases and the data we send to the event creation and think of things we should be validating/testing. For instance, the end time needs to be after the start time (already implemented and tested).
> Add routes for creating events!

- controllers/member.js
- routes/index.js
- routes/member.js
- test/account.js
- test/member.js
- views/member/profile.pug
- views/member/settings.pug
- views/partials/navigation.pug
This doesn't cover everyyythhiinnggg profiles/settings needs to handle, but it's good enough for now. Will leave the technical challenges for later... in fact I'll make issues and put them here
- Add picture for accounts - #17
- Add support for setting super user/private user - #18
Of course the pages also need prettified.
@spkane31 same thing as before - take a look at the behavior of these things/tests and let me know if anything jumps out to you to as a problem.
> Adds Profile capabilities

- controllers/event.js
- routes/event.js
- test/event.js
- views/event/list.pug
This adds a page to `/event` that lists all meetings and events, separately. Its not pretty, but what is on the site?
> Add event list page

- controllers/event.js
- routes/event.js
- test/event.js
- views/event/detail.pug
- views/event/list.pug
Adds an event details page. This leaves out all the logic and endpoints for member signup/hours verification - I'm going to wait on that to do it everywhere it's needed at once
> Event details

- docs/database.md
- docs/dev-guide.md
I added a few lines related to support Windows users struggling with MySQL.
> Added notes for mySQL on Windows to dev-guide.md

- public/stylesheets/style.css
Footer will now stay at the bottom of the page.
> Fixed footer

- public/stylesheets/style.css
- views/layout.pug
- views/partials/footer.pug
- views/partials/navigation.pug
The navbar is now more responsive and no longer a table. It uses CSS flexbox to handle layout/formatting and has hover effects.
> Navbar style

- public/stylesheets/style.css
- views/event/list.pug
- views/event/mixins/list.pug
Hey @shahj14 I'm making this a  PR and requesting your review because I noticed the `event-box` css class wasn't actually defined anywhere - but in doing this it didn't make sense to have a `meeting-box` and `event-box` style. So, I made `meeting-box` `event-box` and just use that - but more importantly, is there anything missing that you intended to be in `event-box`? I know we could be using imported styles from bootstrap but I doubt they have one called `event-box`?
> Add event-list mixin

- controllers/event.js
- controllers/member.js
- docs/database.md
- migrations/20180501211551-create-member.js
- migrations/20180501225518-create-attendance.js
- models/attendance.js
- models/event.js
- models/member.js
- routes/event.js
- test/account.js
- test/attendance.js
- test/common.js
- test/event.js
- test/member.js
- views/event/detail.pug
- views/member/profile.pug
This PR is just for me tracking progress on this branch. I will request reviews when it is ready to merge.
> Attendance Hookups!

- controllers/event.js
- routes/event.js
- test/event.js
- views/event/create.pug
- views/event/detail.pug
Making this a PR so that I can track effort on it.
Todo:
> Add event edit ability - for #33

- controllers/member.js
- public/stylesheets/style.css
- views/event/detail.pug
- views/member/profile.pug
This is a place to iterate on feedback for event detail / member profile styling
> Make initial rough detail/profile styling

- .gitignore
- controllers/member.js
- docs/dev-guide.md
- package-lock.json
- package.json
- public/stylesheets/style.css
- test/member.js
- views/member/mixins/card.pug
- views/member/profile.pug
- views/member/settings.pug
Adds the ability to have custom profile pictures. This will require some configuration once in production.
> Custom Profile Pictures!

- .env.example
- .travis.yml
- controllers/index.js
- docs/dev-guide.md
- routes/index.js
- test/basic.js
- views/member/settings.pug
- views/reset.pug
Adds an endpoint for resetting the website at the end of the semester. Works on a password defined on server in an environment variable
> Site reset

- public/stylesheets/style.css
- views/member/list.pug
- views/member/mixins/hours-table.pug
- views/member/mixins/table.pug
Only viewable to super users. Future plans include adding a toggle between card view and table view along with making the columns sortable.
> Added table for viewing member hours

- package-lock.json
- package.json
> Greenkeeper/sequelize cli 5.2.0

- package-lock.json
- package.json
> Greenkeeper/debug 4.1.0

- docs/production.md
- tools/db_backup.sh
Going to let my cron job for this run overnight just to make sure its successful.
@spkane31 you can read over the documentation additions and let me know if you have any questions, or if you have any concerns with the methodology. 
Once this is working I'll switch it to the ambassadors email on the server
> DB Backup automation!

- controllers/index.js
- package-lock.json
- package.json
- routes/index.js
- test/basic.js
- test/member.js
- views/partials/navigation.pug
- views/training.pug
Added the necessities for a training page including pug file, navigation header, tests, and changes to member.js file.
> added training page

- docs/dev-guide.md
- views/event/detail.pug
Resolve #78 by adding a column that shows hours on signup.
Thoughts @spkane31?
> Show hours on event member listings

- controllers/event.js
- test/event.js
Adds code to not allow events longer than 24 hours. Adds a test as well for that behavior.
@shahj14 you're in charge now, right? I'll put you as a reviewer on PRs
> Disallow events longer than 24hrs. Closes #74

- .env.example
- docs/dev-guide.md
@kurtlewis Added some documentation on the MySQL database installation/creation that I went through while getting it set up on Linux. Thought it's better to have it for future devs.
> added documentation for configuring MySQL databases

- public/stylesheets/style.css
- views/member/mixins/card.pug
- views/member/profile.pug
This pull request addresses #119 and makes new enhancements to the member cards. To fix the issues causing skewed images, I removed one of the constraints (from width and height) to allow the image to fill up to a certain size in one direction. I went ahead also cropped the image into a circle as it looked better with the surrounding text. Circular profile images are also seen used throughout other websites. 
For card enhancements, I decided to add a hierarchy for the textual information displayed on the cards. The colors, font sizes, and grouping together similar content will enforce this hierarchy. A bottom bar is added to the bottom of the card to create balance with the bold text on top. I also turned down the harshness of the shadows as it fits better with this new card enhancements. …
> Fix and enhance member cards

- public/stylesheets/style.css
- views/member/profile.pug
Addressing #57 by updating the styling on the profile page. The style is changed to reflect the new member cards. The inline style is also removed.
> Updating profile page styling

- public/stylesheets/style.css
Updating the styling for alerts to comply with [better minimum contrast ratio](https://www.w3.org/TR/WCAG21/#contrast-minimum). Also updating the margins as there is a large gap appearing when an alert is shown.
> Update alert styling

- public/stylesheets/style.css
Fixing the margin for the main content to allow breathing room at the bottom of the page.
> Fix margin for main content

- public/stylesheets/style.css
- views/apply.pug
- views/calendar.pug
- views/info-booklet.pug
- views/student-orgs.pug
- views/training.pug
- views/virtual-tour.pug
This adds the website tour video under the training tab
This also adds some styling to the tabs with iFrames
> Added website tour video and styling to iframe elements

- docs/tech-design.md
- public/stylesheets/style.css
- views/event/detail.pug
- views/member/list.pug
- views/member/mixins/card.pug
- views/member/mixins/points-table.pug
- views/member/profile.pug
- views/reset.pug
> Change hours verbiage to points

- public/stylesheets/style.css
- views/event/detail.pug
added some styling for toggle switch
> Add toggle switch styling

- app.js
- controllers/event.js
- controllers/member.js
- package-lock.json
Some changes to express lingo that might break env on start up
> Express changes

- models/index.js
> Fix sequelize dependency issue

- views/event/detail.pug
> changed military time in events to EST

- controllers/event.js
- controllers/member.js
- migrations/1.x.x_to_2.0.0.sql
- models/attendance.js
- package-lock.json
- test/account.js
- test/attendance.js
- test/event.js
- views/event/detail.pug
- views/member/profile.pug
The office requested a new button to excuse users from an event. Super users can see who is excused within an event and on a users individual page, but general members cannot see members excused from an event.
> Excused button

- views/student-orgs.pug
Hey Liz or Jeet, please review this PR and verify it for me!
> Tribunal slides added for ambassadors

- views/student-orgs.pug
Updated Student Orgs tab with updated slides.
> Owen branch

- controllers/event.js
- controllers/index.js
- controllers/member.js
- migrations/1.x.x_to_2.0.0.sql
- models/attendance.js
- models/event.js
- models/member.js
- package-lock.json
- public/stylesheets/style.css
- routes/event.js
- test/event.js
- views/event/attendanceStatus.pug
- views/event/create.pug
- views/event/detail.pug
- views/member/mixins/points-table.pug
- views/member/profile.pug
- views/member/settings.pug
- views/student-orgs.pug
Added a feature to track a member's status: In Class or On Co-op.
-- Requires member to update this every 4 months
-- Super Users can change a member's status
Members can now remove their own sign-ups.
-- Member cannot remove a sign-up within 72 hours of an event.
Events now have a limited amount of sign-ups available
-- A member cannot sign up for an event if it has reached its limit
-- Limit is set when the event is made or edited
Super Users can now change a member's event attendance record
-- Amount of events Excused or Did Not Attend are now tracked per member
> 2.0: The Updated Website
